### ISSUE TITLE
could you update your code？

### ISSUE THREAD

**Issue by QC17551** [deepomicslab/SEAT#1]
Your research work is very meaningful !!!
```python
def get_se_for_vertices(M, sparse_m, vG, vs, pV):
    g = get_g(M, sparse_m, vs)
    V = get_v(M, sparse_m, vs)
    return get_se(vG, sparse_m, g, V, pV)


def get_se_for_vertex(M, sparse_m, d, vG, bin, pV):
    if get_se(vG, d[bin], d[bin], pV) != get_se_for_vertices(M, vG, [bin], pV):
        raise ValueError("bin se error")
    return get_se_for_vertex(M, sparse_m, vG, [bin], pV)
```
Both of them are obvious mistake.
I have three question :
- `return get_se(vG, sparse_m, g, V, pV)` the number of args in this function is not same as the definition of `get_se`
- `get_se_for_vertices(M, vG, [bin], pV)` the number of args in this function is not same as the definition of `get_se_for_vertices`
- `get_se_for_vertex(M, sparse_m, vG, [bin], pV)` ,code calls itself recursively with incorrect number of arguments

**Comment by thelingxichen** [comment]
Dear Quichi,

Thanks for your interest. You can directly install SEAT  with the command `pip install pyseat`.

I also update the source codes which match the NAR manuscript at the master branch.

Best,
Lingxi

**Comment by QC17551** [comment]
> Dear Quichi,
> 
> Thanks for your interest. You can directly install SEAT with the command `pip install pyseat`.
> 
> I also update the source codes which match the NAR manuscript at the master branch.
> 
> Best, Lingxi

Thanks for your answer!
